server:
  port: 8082
spring:
  application:
    name: firstdemoclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: first01-8082-66
    hostname: willdo
