server:
  port: 8082
spring:
  application:
    name: firstdemoclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: firstdemo_${server.port}
    prefer-ip-address: true
#    ip-address: 192.168.1.1
#    hostname: hostname_test

management:
  endpoint:
    health:
      show-details: always