server:
  port: 7007
spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 1432476945@qq.com
    password: rrukuykvfdtwbafh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          connectiontimeout: 3000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
