server:
  port: 8091
spring:
  application:
    name: seconddemoclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: seconddemo_${server.port}
#    hostname: willdo

