server:
  port: 8091
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  application:
    name: seconddemoclient


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: seconddemo_${server.port}
#    hostname: willdo
feign:
  hystrix:
    enabled: true



#logging:
#  level:
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug
