server:
  port: 8091
#spring:
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1
#  application:
#    name: seconddemoclient
#
#  rabbitmq:
#    host: 10.127.6.209
#    port: 5672
#    username: guest
#    password: guest


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#  instance:
#    instance-id: seconddemo_${server.port}
#    prefer-ip-address: true
#
#feign:
#  hystrix:
#    enabled: true


#logging:
#  level:
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug


#logging:
#  file:
#    name: E:\logs\hello-word\system1.log
#    path: E:\logs\seconddemo
#  pattern:
#    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
#  level:
#    root: info
