server:
  port: 8031
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: gateway_${server.port}


management:
  endpoint:
    health:
      show-details: always
zuul:
  routes:
    firstdemo_service:
      path: /first/**
      serviceId: firstdemoclient
